# Australia-Wide Real Estate Seed Dataset (Rent & Sale)
# Covers NSW, VIC, QLD, WA, SA, ACT, TAS across major cities and regional hubs

AUSTRALIA_LISTINGS = [
    # ==========================
    # FOR SALE - NSW (Regional & Metro)
    # ==========================
    {
        "id": "sale_nsw_2541_01",
        "url": "https://www.realestate.com.au/property-house-nsw-nowra-14250101",
        "title": "Charming Renovated 4-Bedroom Coastal Home with Large Yard",
        "street": "28 Shoalhaven Street",
        "suburb": "Nowra",
        "state": "NSW",
        "postcode": "2541",
        "price": 820000,
        "listing_type": "sale",
        "beds": 4,
        "baths": 2,
        "cars": 2,
        "prop_type": "House",
        "image_url": "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80",
        "lat": -34.8712,
        "lng": 150.6045,
        "inspection_date": "2026-10-10T11:00:00+11:00",
        "description": "Exquisitely renovated 4-bedroom family haven on a generous 720sqm block in central Nowra. Features modern open-plan living, stone kitchen benchtops, split-system air conditioning, sparkling in-ground pool, and a fully fenced dog-friendly yard. Minutes to Shoalhaven River and CBD shops.",
        "source": "domain.com.au",
        "pets_allowed": 1,
        "features": ["pets", "pool", "aircon", "yard"]
    },
    {
        "id": "sale_nsw_2541_02",
        "url": "https://www.realestate.com.au/property-house-nsw-bomaderry-14250102",
        "title": "Contemporary Low-Maintenance Living Close to Station",
        "street": "42 Cambewarra Road",
        "suburb": "Bomaderry",
        "state": "NSW",
        "postcode": "2541",
        "price": 595000,
        "listing_type": "sale",
        "beds": 3,
        "baths": 1,
        "cars": 1,
        "prop_type": "House",
        "image_url": "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=80",
        "lat": -34.8488,
        "lng": 150.6092,
        "inspection_date": "2026-10-11T12:30:00+11:00",
        "description": "Ideal first home or investment in booming Bomaderry. Light-filled interiors, polished timber floorboards, undercover alfresco entertaining deck, and secure pet-friendly garden. Easy walk to Bomaderry train station with Sydney express services.",
        "source": "realestate.com.au",
        "pets_allowed": 1,
        "features": ["pets", "yard", "aircon"]
    },
    {
        "id": "sale_nsw_2541_03",
        "url": "https://www.realestate.com.au/property-townhouse-nsw-nowra-14250103",
        "title": "Boutique Modern Townhouse in Quiet Enclave",
        "street": "7/15 Plunkett Street",
        "suburb": "Nowra",
        "state": "NSW",
        "postcode": "2541",
        "price": 485000,
        "listing_type": "sale",
        "beds": 2,
        "baths": 1,
        "cars": 1,
        "prop_type": "Townhouse",
        "image_url": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
        "lat": -34.8735,
        "lng": 150.6010,
        "inspection_date": "2026-10-10T10:00:00+11:00",
        "description": "Modern two-storey townhouse with private courtyard. Open plan living, designer kitchen with stainless steel appliances, solar hot water, and reverse cycle air conditioning. Affordable strata levies in a secure complex.",
        "source": "raywhite.com.au",
        "pets_allowed": 1,
        "features": ["pets", "aircon", "solar"]
    },
    {
        "id": "sale_nsw_syd_01",
        "url": "https://www.realestate.com.au/property-apartment-nsw-sydney-14250104",
        "title": "Luxury High-Rise Executive Apartment with Harbour Panoramas",
        "street": "1802/161 Castlereagh Street",
        "suburb": "Sydney",
        "state": "NSW",
        "postcode": "2000",
        "price": 1450000,
        "listing_type": "sale",
        "beds": 2,
        "baths": 2,
        "cars": 1,
        "prop_type": "Apartment",
        "image_url": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
        "lat": -33.8715,
        "lng": 151.2093,
        "inspection_date": "2026-10-10T13:00:00+11:00",
        "description": "Spectacular luxury apartment in the prestigious Sydney CBD precinct. Floor-to-ceiling glass capturing panoramic city lights, marble kitchen, master ensuite, ducted climate control, resident pool, sauna, and concierge service.",
        "source": "domain.com.au",
        "pets_allowed": 1,
        "features": ["pets", "pool", "aircon", "balcony"]
    },
    {
        "id": "sale_nsw_syd_02",
        "url": "https://www.realestate.com.au/property-terrace-nsw-newtown-14250105",
        "title": "Classic Victorian Terrace in Vibrantly Quiet Street",
        "street": "24 Darley Street",
        "suburb": "Newtown",
        "state": "NSW",
        "postcode": "2042",
        "price": 1680000,
        "listing_type": "sale",
        "beds": 3,
        "baths": 2,
        "cars": 1,
        "prop_type": "House",
        "image_url": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
        "lat": -33.8967,
        "lng": 151.1798,
        "inspection_date": "2026-10-11T11:30:00+11:00",
        "description": "Timeless elegance meets designer contemporary flair in this Newtown terrace. Ornate high ceilings, bespoke timber cabinetry, sun-drenched private courtyard garden, and rear-lane parking access. Stroll to King Street cafes and Sydney University.",
        "source": "realestate.com.au",
        "pets_allowed": 1,
        "features": ["pets", "yard", "aircon"]
    },
    {
        "id": "sale_nsw_syd_03",
        "url": "https://www.realestate.com.au/property-house-nsw-manly-14250106",
        "title": "Coastal Beachside Oasis with Ocean Breezes",
        "street": "14 Marine Parade",
        "suburb": "Manly",
        "state": "NSW",
        "postcode": "2095",
        "price": 2450000,
        "listing_type": "sale",
        "beds": 3,
        "baths": 2,
        "cars": 2,
        "prop_type": "Townhouse",
        "image_url": "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=80",
        "lat": -33.7995,
        "lng": 151.2885,
        "inspection_date": "2026-10-10T14:30:00+11:00",
        "description": "World-class coastal lifestyle just steps from Manly Beach and Shelly Beach. Expansive wraparound sun deck, heated pool, dual living zones, double lockup garage, and state-of-the-art security.",
        "source": "domain.com.au",
        "pets_allowed": 1,
        "features": ["pets", "pool", "aircon", "balcony"]
    },
    {
        "id": "sale_nsw_woll_01",
        "url": "https://www.realestate.com.au/property-house-nsw-wollongong-14250107",
        "title": "Illawarra Coastal Living with Escarpment Views",
        "street": "52 Cliff Road",
        "suburb": "Wollongong",
        "state": "NSW",
        "postcode": "2500",
        "price": 1250000,
        "listing_type": "sale",
        "beds": 3,
        "baths": 2,
        "cars": 2,
        "prop_type": "House",
        "image_url": "https://images.unsplash.com/photo-1598228723793-52759bba239c?auto=format&fit=crop&w=800&q=80",
        "lat": -34.4215,
        "lng": 150.9025,
        "inspection_date": "2026-10-10T12:00:00+11:00",
        "description": "Prime beachside address overlooking Wollongong Harbour and North Beach. Architecturally designed, wide entertaining balcony, landscaped gardens, and double garage.",
        "source": "realestate.com.au",
        "pets_allowed": 1,
        "features": ["pets", "aircon", "balcony", "yard"]
    },

    # ==========================
    # FOR SALE - VIC (Melbourne & Regional)
    # ==========================
    {
        "id": "sale_vic_mel_01",
        "url": "https://www.realestate.com.au/property-house-vic-richmond-14250201",
        "title": "Stunning Double-Fronted Victorian with North-Facing Garden",
        "street": "18 Lennox Street",
        "suburb": "Richmond",
        "state": "VIC",
        "postcode": "3121",
        "price": 1340000,
        "listing_type": "sale",
        "beds": 3,
        "baths": 2,
        "cars": 1,
        "prop_type": "House",
        "image_url": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
        "lat": -37.8225,
        "lng": 144.9965,
        "inspection_date": "2026-10-10T11:00:00+11:00",
        "description": "Showcasing a harmonious blend of period character and Scandinavian-inspired minimalist renovation. Expansive open-plan living opening out to an idyllic deck, hydronic heating, air conditioning, and solar panels.",
        "source": "domain.com.au",
        "pets_allowed": 1,
        "features": ["pets", "yard", "aircon", "solar"]
    },
    {
        "id": "sale_vic_mel_02",
        "url": "https://www.realestate.com.au/property-apartment-vic-south-yarra-14250202",
        "title": "Designer Apartment in Botanic Garden Precinct",
        "street": "402/28 Garden Street",
        "suburb": "South Yarra",
        "state": "VIC",
        "postcode": "3141",
        "price": 685000,
        "listing_type": "sale",
        "beds": 2,
        "baths": 2,
        "cars": 1,
        "prop_type": "Apartment",
        "image_url": "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
        "lat": -37.8415,
        "lng": 144.9912,
        "inspection_date": "2026-10-11T13:30:00+11:00",
        "description": "Sleek and sophisticated living directly opposite leafy parklands. Miele kitchen appliances, engineered oak floors, European laundry, covered balcony with CBD views, and basement parking.",
        "source": "realestate.com.au",
        "pets_allowed": 1,
        "features": ["pets", "aircon", "balcony"]
    },
    {
        "id": "sale_vic_gee_01",
        "url": "https://www.realestate.com.au/property-house-vic-geelong-14250203",
        "title": "Character Californian Bungalow in Geelong West",
        "street": "76 Shannon Avenue",
        "suburb": "Geelong",
        "state": "VIC",
        "postcode": "3220",
        "price": 760000,
        "listing_type": "sale",
        "beds": 3,
        "baths": 2,
        "cars": 2,
        "prop_type": "House",
        "image_url": "https://images.unsplash.com/photo-1576941089067-2de3c901e126?auto=format&fit=crop&w=800&q=80",
        "lat": -38.1450,
        "lng": 144.3460,
        "inspection_date": "2026-10-10T10:30:00+11:00",
        "description": "Charming period bungalow with leadlight windows, decorative plaster ceilings, solar power, and spacious level backyard perfect for children and pets. Moments to Pakington Street cafes.",
        "source": "domain.com.au",
        "pets_allowed": 1,
        "features": ["pets", "yard", "solar", "aircon"]
    },

    # ==========================
    # FOR SALE - QLD (Brisbane & Gold Coast)
    # ==========================
    {
        "id": "sale_qld_bne_01",
        "url": "https://www.realestate.com.au/property-house-qld-new-farm-14250301",
        "title": "Quintessential New Farm Queenslander with Magnesium Pool",
        "street": "82 Merthyr Road",
        "suburb": "Brisbane",
        "state": "QLD",
        "postcode": "4005",
        "price": 1890000,
        "listing_type": "sale",
        "beds": 4,
        "baths": 3,
        "cars": 2,
        "prop_type": "House",
        "image_url": "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80",
        "lat": -27.4690,
        "lng": 153.0485,
        "inspection_date": "2026-10-10T11:00:00+11:00",
        "description": "Breathtaking heritage Queenslander boasting wrap-around verandahs, high VJ walls, resort-style heated magnesium pool, covered outdoor BBQ pavilion, and secure fenced yard in Brisbane's premier riverside enclave.",
        "source": "domain.com.au",
        "pets_allowed": 1,
        "features": ["pets", "pool", "aircon", "yard", "solar"]
    },
    {
        "id": "sale_qld_gc_01",
        "url": "https://www.realestate.com.au/property-villa-qld-surfers-paradise-14250302",
        "title": "Sun-Drenched Waterfront Villa with Private Pontoon",
        "street": "14 Amalfi Drive",
        "suburb": "Surfers Paradise",
        "state": "QLD",
        "postcode": "4217",
        "price": 1650000,
        "listing_type": "sale",
        "beds": 4,
        "baths": 3,
        "cars": 2,
        "prop_type": "Villa",
        "image_url": "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?auto=format&fit=crop&w=800&q=80",
        "lat": -28.0095,
        "lng": 153.4210,
        "inspection_date": "2026-10-11T12:00:00+11:00",
        "description": "Luxury Gold Coast canal-front villa featuring main river boat access, private jetty, plunge pool, soaring ceilings, ducted air con, and pet-friendly riverside terrace.",
        "source": "realestate.com.au",
        "pets_allowed": 1,
        "features": ["pets", "pool", "aircon", "balcony"]
    },

    # ==========================
    # FOR SALE - WA (Perth)
    # ==========================
    {
        "id": "sale_wa_per_01",
        "url": "https://www.realestate.com.au/property-house-wa-cottesloe-14250401",
        "title": "Sunset Coastal Residence Walking Distance to Ocean",
        "street": "29 View Street",
        "suburb": "Perth",
        "state": "WA",
        "postcode": "6011",
        "price": 1950000,
        "listing_type": "sale",
        "beds": 4,
        "baths": 2,
        "cars": 2,
        "prop_type": "House",
        "image_url": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80",
        "lat": -31.9960,
        "lng": 115.7580,
        "inspection_date": "2026-10-10T14:00:00+08:00",
        "description": "Prime Cottesloe coastal home offering ocean vistas, soaring timber raked ceilings, heated lap pool, expansive entertainer's deck, and large lawn for dogs and family.",
        "source": "domain.com.au",
        "pets_allowed": 1,
        "features": ["pets", "pool", "aircon", "yard"]
    },

    # ==========================
    # FOR SALE - SA (Adelaide)
    # ==========================
    {
        "id": "sale_sa_adl_01",
        "url": "https://www.realestate.com.au/property-house-sa-norwood-14250501",
        "title": "Grand Sandstone Villa with Modern Architectural Extension",
        "street": "92 The Parade",
        "suburb": "Adelaide",
        "state": "SA",
        "postcode": "5067",
        "price": 1180000,
        "listing_type": "sale",
        "beds": 4,
        "baths": 2,
        "cars": 2,
        "prop_type": "House",
        "image_url": "https://images.unsplash.com/photo-1588880331179-bc9b93a8cb5e?auto=format&fit=crop&w=800&q=80",
        "lat": -34.9210,
        "lng": 138.6360,
        "inspection_date": "2026-10-10T10:30:00+09:30",
        "description": "Magnificent sandstone villa in tightly held Norwood. Character archways, polished cellar, custom kitchen with butler pantry, north-facing manicured garden, and solar power.",
        "source": "realestate.com.au",
        "pets_allowed": 1,
        "features": ["pets", "yard", "solar", "aircon"]
    },

    # ==========================
    # FOR SALE - ACT (Canberra)
    # ==========================
    {
        "id": "sale_act_cbr_01",
        "url": "https://www.realestate.com.au/property-house-act-ainslie-14250601",
        "title": "Inner-North Extended Heritage Home with Bushland Backdrop",
        "street": "18 Higgins Crescent",
        "suburb": "Canberra",
        "state": "ACT",
        "postcode": "2602",
        "price": 1150000,
        "listing_type": "sale",
        "beds": 4,
        "baths": 2,
        "cars": 2,
        "prop_type": "House",
        "image_url": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80",
        "lat": -35.2640,
        "lng": 149.1480,
        "inspection_date": "2026-10-10T11:30:00+11:00",
        "description": "Quietly positioned at the foot of Mount Ainslie nature reserve. Generous block with vegetable garden, double-glazed windows, ducted reverse-cycle heating/cooling, and sunny pet-friendly yard.",
        "source": "allhomes.com.au",
        "pets_allowed": 1,
        "features": ["pets", "yard", "aircon", "solar"]
    },

    # ==========================
    # FOR SALE - TAS (Hobart)
    # ==========================
    {
        "id": "sale_tas_hob_01",
        "url": "https://www.realestate.com.au/property-house-tas-battery-point-14250701",
        "title": "Historic Georgian Maritime Cottage in Battery Point",
        "street": "22 Hampden Road",
        "suburb": "Hobart",
        "state": "TAS",
        "postcode": "7004",
        "price": 1390000,
        "listing_type": "sale",
        "beds": 3,
        "baths": 2,
        "cars": 1,
        "prop_type": "House",
        "image_url": "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
        "lat": -42.8895,
        "lng": 147.3325,
        "inspection_date": "2026-10-11T12:00:00+11:00",
        "description": "Rare heritage treasure in historic Battery Point. Exposed brick and timber beam details, sunny rear courtyard garden, Derwent River views, and a brief stroll down Kelly's Steps to Salamanca Market.",
        "source": "realestate.com.au",
        "pets_allowed": 1,
        "features": ["pets", "yard", "balcony"]
    },

    # ==========================
    # FOR RENT - AUSTRALIA-WIDE METRO & REGIONAL
    # ==========================
    {
        "id": "rent_nsw_syd_01",
        "url": "https://www.rent.com.au/property/1202-178-george-st-sydney-nsw-2000",
        "title": "1202/178 George Street, Sydney NSW 2000",
        "street": "1202/178 George Street",
        "suburb": "Sydney",
        "state": "NSW",
        "postcode": "2000",
        "price": 880,
        "listing_type": "rent",
        "beds": 1,
        "baths": 1,
        "cars": 0,
        "prop_type": "Apartment",
        "image_url": "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
        "lat": -33.8610,
        "lng": 151.2080,
        "inspection_date": "2026-10-09T17:00:00+11:00",
        "description": "Furnished executive 1-bedroom apartment in the heart of The Rocks and Circular Quay. Ducted air conditioning, full gym, indoor heated swimming pool, and 24hr security.",
        "source": "rent.com.au",
        "pets_allowed": 0,
        "features": ["pool", "aircon"]
    },
    {
        "id": "rent_nsw_syd_02",
        "url": "https://www.rent.com.au/property/45-victoria-rd-parramatta-nsw-2150",
        "title": "45 Victoria Road, Parramatta NSW 2150",
        "street": "45 Victoria Road",
        "suburb": "Parramatta",
        "state": "NSW",
        "postcode": "2150",
        "price": 620,
        "listing_type": "rent",
        "beds": 2,
        "baths": 2,
        "cars": 1,
        "prop_type": "Unit",
        "image_url": "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80",
        "lat": -33.8125,
        "lng": 151.0085,
        "inspection_date": "2026-10-08T16:30:00+11:00",
        "description": "Spacious two-bedroom unit with master ensuite, gas cooktop, built-in wardrobes, secure parking space, and large private balcony. Pets considered on application.",
        "source": "rent.com.au",
        "pets_allowed": 1,
        "features": ["pets", "aircon", "balcony"]
    },
    {
        "id": "rent_nsw_byron_01",
        "url": "https://www.rent.com.au/property/18-fletcher-st-byron-bay-nsw-2481",
        "title": "18 Fletcher Street, Byron Bay NSW 2481",
        "street": "18 Fletcher Street",
        "suburb": "Byron Bay",
        "state": "NSW",
        "postcode": "2481",
        "price": 750,
        "listing_type": "rent",
        "beds": 2,
        "baths": 1,
        "cars": 1,
        "prop_type": "Villa",
        "image_url": "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80",
        "lat": -28.6435,
        "lng": 153.6120,
        "inspection_date": "2026-10-10T10:00:00+11:00",
        "description": "Tranquil beachside villa just 300m to Main Beach. Timber deck surrounded by tropical palms, outdoor hot shower, air conditioning, and pet friendly garden.",
        "source": "domain.com.au",
        "pets_allowed": 1,
        "features": ["pets", "yard", "aircon", "balcony"]
    },
    {
        "id": "rent_vic_mel_01",
        "url": "https://www.rent.com.au/property/804-250-elizabeth-st-melbourne-vic-3000",
        "title": "804/250 Elizabeth Street, Melbourne VIC 3000",
        "street": "804/250 Elizabeth Street",
        "suburb": "Melbourne",
        "state": "VIC",
        "postcode": "3000",
        "price": 540,
        "listing_type": "rent",
        "beds": 1,
        "baths": 1,
        "cars": 0,
        "prop_type": "Apartment",
        "image_url": "https://images.unsplash.com/photo-1502005229762-ee1b403487c8?auto=format&fit=crop&w=800&q=80",
        "lat": -37.8120,
        "lng": 144.9630,
        "inspection_date": "2026-10-09T12:30:00+11:00",
        "description": "Inner-city sanctuary in Melbourne's Free Tram Zone. Light-filled living, stone benchtops, split system AC, and building gym and swimming pool.",
        "source": "realestate.com.au",
        "pets_allowed": 0,
        "features": ["pool", "aircon"]
    },
    {
        "id": "rent_vic_mel_02",
        "url": "https://www.rent.com.au/property/34-chapel-st-south-yarra-vic-3141",
        "title": "34 Chapel Street, South Yarra VIC 3141",
        "street": "34 Chapel Street",
        "suburb": "South Yarra",
        "state": "VIC",
        "postcode": "3141",
        "price": 720,
        "listing_type": "rent",
        "beds": 2,
        "baths": 2,
        "cars": 1,
        "prop_type": "Townhouse",
        "image_url": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80",
        "lat": -37.8420,
        "lng": 144.9925,
        "inspection_date": "2026-10-10T14:00:00+11:00",
        "description": "Contemporary two-bedroom townhouse with private courtyard. Pet friendly, internal laundry, secure garage, and reverse cycle air conditioning throughout.",
        "source": "domain.com.au",
        "pets_allowed": 1,
        "features": ["pets", "yard", "aircon"]
    },
    {
        "id": "rent_qld_bne_01",
        "url": "https://www.rent.com.au/property/1502-100-queen-st-brisbane-city-qld-4000",
        "title": "1502/100 Queen Street, Brisbane City QLD 4000",
        "street": "1502/100 Queen Street",
        "suburb": "Brisbane",
        "state": "QLD",
        "postcode": "4000",
        "price": 680,
        "listing_type": "rent",
        "beds": 2,
        "baths": 2,
        "cars": 1,
        "prop_type": "Apartment",
        "image_url": "https://images.unsplash.com/photo-1567496898669-ee935f5f647a?auto=format&fit=crop&w=800&q=80",
        "lat": -27.4705,
        "lng": 153.0260,
        "inspection_date": "2026-10-09T13:00:00+10:00",
        "description": "Stunning river views from the 15th floor. Fully air-conditioned, resident infinity pool, sauna, gym, and 24/7 building management.",
        "source": "rent.com.au",
        "pets_allowed": 1,
        "features": ["pets", "pool", "aircon", "balcony"]
    },
    {
        "id": "rent_qld_gc_01",
        "url": "https://www.rent.com.au/property/28-elkhorn-ave-surfers-paradise-qld-4217",
        "title": "28 Elkhorn Avenue, Surfers Paradise QLD 4217",
        "street": "28 Elkhorn Avenue",
        "suburb": "Surfers Paradise",
        "state": "QLD",
        "postcode": "4217",
        "price": 590,
        "listing_type": "rent",
        "beds": 2,
        "baths": 1,
        "cars": 1,
        "prop_type": "Unit",
        "image_url": "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?auto=format&fit=crop&w=800&q=80",
        "lat": -28.0015,
        "lng": 153.4290,
        "inspection_date": "2026-10-10T11:00:00+10:00",
        "description": "Bright and breezy beachside unit, 2 minutes walk to the patrolled surf beach. Resort pool, secure parking, sunny north-facing balcony, and pet friendly.",
        "source": "domain.com.au",
        "pets_allowed": 1,
        "features": ["pets", "pool", "aircon", "balcony"]
    },
    {
        "id": "rent_wa_per_01",
        "url": "https://www.rent.com.au/property/18-st-georges-tce-perth-wa-6000",
        "title": "18 St Georges Terrace, Perth WA 6000",
        "street": "18 St Georges Terrace",
        "suburb": "Perth",
        "state": "WA",
        "postcode": "6000",
        "price": 580,
        "listing_type": "rent",
        "beds": 2,
        "baths": 2,
        "cars": 1,
        "prop_type": "Apartment",
        "image_url": "https://images.unsplash.com/photo-1502672023488-70e25813eb80?auto=format&fit=crop&w=800&q=80",
        "lat": -31.9560,
        "lng": 115.8610,
        "inspection_date": "2026-10-09T16:30:00+08:00",
        "description": "Inner-city apartment overlooking Government House Gardens. Modern kitchen, ducted air con, secure car bay, swimming pool, and pet friendly policy.",
        "source": "realestate.com.au",
        "pets_allowed": 1,
        "features": ["pets", "pool", "aircon"]
    },
    {
        "id": "rent_sa_adl_01",
        "url": "https://www.rent.com.au/property/45-king-william-st-adelaide-sa-5000",
        "title": "45 King William Street, Adelaide SA 5000",
        "street": "45 King William Street",
        "suburb": "Adelaide",
        "state": "SA",
        "postcode": "5000",
        "price": 510,
        "listing_type": "rent",
        "beds": 2,
        "baths": 1,
        "cars": 1,
        "prop_type": "Apartment",
        "image_url": "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80",
        "lat": -34.9285,
        "lng": 138.6000,
        "inspection_date": "2026-10-10T12:00:00+09:30",
        "description": "Central Adelaide apartment with high ceilings, timber floors, modern kitchen with dishwasher, and walking distance to Rundle Mall and Adelaide University.",
        "source": "rent.com.au",
        "pets_allowed": 1,
        "features": ["pets", "aircon"]
    },
    {
        "id": "rent_act_cbr_01",
        "url": "https://www.rent.com.au/property/22-eyre-st-kingston-act-2604",
        "title": "22 Eyre Street, Kingston ACT 2604",
        "street": "22 Eyre Street",
        "suburb": "Canberra",
        "state": "ACT",
        "postcode": "2604",
        "price": 650,
        "listing_type": "rent",
        "beds": 2,
        "baths": 2,
        "cars": 1,
        "prop_type": "Apartment",
        "image_url": "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=800&q=80",
        "lat": -35.3180,
        "lng": 149.1440,
        "inspection_date": "2026-10-10T10:00:00+11:00",
        "description": "Spacious Kingston Foreshore apartment. Dual master suites with private ensuites, stone kitchen with European appliances, and ducted heating/cooling. Pets welcome upon application.",
        "source": "allhomes.com.au",
        "pets_allowed": 1,
        "features": ["pets", "aircon", "balcony"]
    },
    {
        "id": "rent_tas_hob_01",
        "url": "https://www.rent.com.au/property/34-sandy-bay-rd-sandy-bay-tas-7005",
        "title": "34 Sandy Bay Road, Sandy Bay TAS 7005",
        "street": "34 Sandy Bay Road",
        "suburb": "Hobart",
        "state": "TAS",
        "postcode": "7005",
        "price": 560,
        "listing_type": "rent",
        "beds": 3,
        "baths": 1,
        "cars": 1,
        "prop_type": "House",
        "image_url": "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=800&q=80",
        "lat": -42.8980,
        "lng": 147.3310,
        "inspection_date": "2026-10-10T13:00:00+11:00",
        "description": "Classic character cottage in Sandy Bay. Timber floorboards, gas heating, sunny vegetable garden, pet friendly yard, and close to UTAS Sandy Bay campus.",
        "source": "domain.com.au",
        "pets_allowed": 1,
        "features": ["pets", "yard"]
    }
]
